### ISSUE TITLE
Would you do me a favor and update the PyPi release?

### ISSUE THREAD

**Issue by larrynung** [mmatuson/SchemaObject#16]
Would you do me a favor and update the PyPi release?

I wanna use for SchemaSync.

Thanks

**Comment by mitsh** [comment]
hey, i've just compiled and uploaded to pypi, please check it and tell me is it working properly.

**Comment by larrynung** [comment]
Sorry, still have invisible character in code

https://github.com/mmatuson/SchemaObject/pull/18

**Comment by mitsh** [comment]
i've merged and sent another release for this project. could you try again?

**Comment by larrynung** [comment]
It's work, thx.

**Comment by mitsh** [comment]
thanks for your contribution
